### PR TITLE
Add Ability to Define App Specific Configuration

### PR DESCRIPTION
**Pull request by bruschke**
Using an umbrella application this pull request would allow you to define different storage accounts and blob containers for different applications.

### CODE REVIEW

**Comment by bruschke** [comment]
@jakobht Just curious if you think you'll have time to review this?

**Comment by jakobht** [comment]
Hi this looks great - do you think it would be possible to write a test or two for this, just to make sure it doesn't break?

**Comment by jakobht** [comment]
I also fixed the CI, so if you merge with master you should be able to pass CI now

**Comment by bruschke** [comment]
Added a new test file for the changes.

**Comment by bruschke** [comment]
This did not end up working as expected.  Tried to replicate the functionality used by https://github.com/xerions/phoenix_swagger/blob/46624104d48d92912207b5ceb08d200f3f53b273/lib/mix/tasks/swagger.generate.ex#L28 but apparently this is only available during compile time, not runtime.

**Pull request closed without merging**
