### PR TITLE
Implemented SAS urls for blob storage

### PR DESCRIPTION
**Pull request by cblavier**
Hey, I just created this service a few weeks ago to generate SAS URLs on Blob storage resources.
https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas

Working fine so far, hope you'll find it useful 👍

### CODE REVIEW

**Comment by jakobht** [comment]
Thanks a lot! I think this is very useful. I have read the code and it looks good - I have not yet done any testing. 
We try to support all current versions of Elixir (so 1.10 - 1.14), using `:hour` in `DateTime.add` is not supported in the older versions. I think the easy fix is to just set the default expiry to `{:second, 3600}`, then it's still possible to use `:hour` if your Elixir version supports it. 
What do you think? :) 

Thanks again, will definitely merge!

**Comment by cblavier** [comment]
> What do you think? :)

sure, I will fix it

**Comment by cblavier** [comment]
Just switched to `{:second, 3600}`, let's see what CI thinks 👀

**Comment by jakobht** [comment]
Awesome! Thanks - I'll test and merge this week

**Comment by jakobht** [comment]
Hi 
I'm sorry, but I just ran a test against Azurite, and I can't get the code to generate the correct signature. I tried a couple of different things, but I didn't manage to get it working, I just get an unauthorized response. 
I tried generating the same SAS using the storage explorer, and there I get a different signature than the code gives (even after changing the versions). 
Unfortunately the storage explorer does not log the string it signed, so I can't see what is wrong. 

I do not have more time today, but I'll have a look when I have some more time. 

The two generated signatures are:

1. From storage explorer:
`http://127.0.0.1:10000/devstoreaccount1/test/test_blob?sv=2018-03-28&st=2022-10-30T14%3A13%3A00Z&se=2022-10-30T15%3A13%3A00Z&sr=b&sp=r&sig=V75WwBitq2W0%2BpVjUJVju1DgpoorMiEp9Qhq3hMc4Rw%3D
`
2. From the code (after changing the version string) 
`http://127.0.0.1:10000/devstoreaccount1/test/test_blob?sv=2018-03-28&st=2022-10-30T14%3A13%3A00Z&se=2022-10-30T15%3A13%3A00Z&sr=b&sp=r&sig=wqcJiWljpaVknEiYGV3Gi15Lsg2eB8v%2B2RaCQro0puA%3D`

The last signature can be generated by changing the version string to `2018-03-28`, and then running this code (the storage account key here is the default one for Azurite, so it's not a problem to share :smile:):
```elixir
iex(1)> Application.put_env(:azurex, Azurex.Blob.Config,
...(1)>   storage_account_connection_string:
...(1)>     "AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1"
...(1)> )
:ok
iex(2)> {_, st, _} = DateTime.from_iso8601("2022-10-30T14:13:00Z", Calendar.ISO, :extended)
{:ok, ~U[2022-10-30 14:13:00Z], 0}
iex(3)> Azurex.Blob.SharedAccessSignature.sas_url("test", "test_blob", from: st, expiry: {:hour, 1}, resource_type: :blob)
"http://127.0.0.1:10000/devstoreaccount1/test/test_blob?sv=2018-03-28&st=2022-10-30T14%3A13%3A00Z&se=2022-10-30T15%3A13%3A00Z&sr=b&sp=r&sig=wqcJiWljpaVknEiYGV3Gi15Lsg2eB8v%2B2RaCQro0puA%3D"
```

**Comment by ShahneRodgers** [comment]
> Hi I'm sorry, but I just ran a test against Azurite, and I can't get the code to generate the correct signature. I tried a couple of different things, but I didn't manage to get it working, I just get an unauthorized response. I tried generating the same SAS using the storage explorer, and there I get a different signature than the code gives (even after changing the versions). Unfortunately the storage explorer does not log the string it signed, so I can't see what is wrong.

I have SAS urls working against Azurite locally (didn't get a chance to push before this PR was made, unfortunately). I think the issue is that line #87 generates a timestamp with "T" in it, whereas Azurite seems to expect one with a space instead. So changing it to 

```
String.replace(se(from, expiry), "T", " ")
```

should work? I haven't tested this branch though, and it's not actually in the docs, so I haven't had a chance to figure out if this is an Azurite bug that will break on Azure.

**Comment by cblavier** [comment]
I never trid Azurite (didn't even know it existed) but it's working for me in production.
Will try with Azurite though as well as @ShahneRodgers suggestion!

**Comment by cblavier** [comment]
Just tried with your code on my production Azure environment, it's working.
But If I do the `String.replace(se(from, expiry), "T", " ")` trick it's not working anymore.

Will try with azurite now

```elixir
iex(1)> path = "indie-bites-43c183b9-5e59-4611-af66-7bea4520d07f.mp3"                      
"indie-bites-43c183b9-5e59-4611-af66-7bea4520d07f.mp3"
iex(2)> container = "readable-audio-original"                                              
"readable-audio-original"
iex(3)> {_, st, _} = DateTime.from_iso8601("2022-10-31T07:30:00Z", Calendar.ISO, :extended)
{:ok, ~U[2022-10-31 07:30:00Z], 0}
iex(4)> sas_url(container, path, resource_type: :blob, from: st, expiry: {:day, 1}) 
"https://readable.blob.core.windows.net/readable-audio-original/indie-bites-43c183b9-5e59-4611-af66-7bea4520d07f.mp3?sv=2020-12-06&st=2022-10-31T07%3A30%3A00Z&se=2022-11-01T07%3A30%3A00Z&sr=b&sp=r&sig=aXvkra%2FBU9jCoduZa07W4MTOVQB9oNOdsdySDtPRKWo%3D"
```

**Comment by cblavier** [comment]
This is working as well with Azurite running on my mac 🤷‍♂️
The difference might be that I did not use a `connection_string`?

```elixir
config :azurex, Azurex.Blob.Config,
  storage_account_name: "devstoreaccount1",
  storage_account_key:
    "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
```

**Comment by cblavier** [comment]
Working with connection string as well, sorry but I have no clue 🤔 

Though, I have a question regarding your message: you wrote that you changed the version to `2018-03-28`. Why so?

My code has only been tested against `2020-12-06` specifications, which have evolved a lot. The 2018 version you are referring to uses a different signature string.

https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#construct-the-signature-string

**Comment by jakobht** [comment]
> Working with connection string as well, sorry but I have no clue thinking
 
Thanks a lot for your testing, and very strange that I could not make it work yesterday, I'll try again today. 

> Though, I have a question regarding your message: you wrote that you changed the version to `2018-03-28`. Why so?
> 
> My code has only been tested against `2020-12-06` specifications, which have evolved a lot. The 2018 version you are referring to uses a different signature string.
> https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#construct-the-signature-string

Yeah I tried the code "as-is" first, and had the problem, then I just wanted to see if I could reproduce what the StorageExplorer gave me, at that uses version 2018-03-28, so that's why i changed it. 

I'll do some more testing, maybe I just did something stupid. Will definetly try against the real blob storage first, maybe my Azurite is acting strange.

**Comment by ShahneRodgers** [comment]
> Just tried with your code on my production Azure environment, it's working. But If I do the `String.replace(se(from, expiry), "T", " ")` trick it's not working anymore.
> 
> Will try with azurite now
> 
> ```elixir
> iex(1)> path = "indie-bites-43c183b9-5e59-4611-af66-7bea4520d07f.mp3"                      
> "indie-bites-43c183b9-5e59-4611-af66-7bea4520d07f.mp3"
> iex(2)> container = "readable-audio-original"                                              
> "readable-audio-original"
> iex(3)> {_, st, _} = DateTime.from_iso8601("2022-10-31T07:30:00Z", Calendar.ISO, :extended)
> {:ok, ~U[2022-10-31 07:30:00Z], 0}
> iex(4)> sas_url(container, path, resource_type: :blob, from: st, expiry: {:day, 1}) 
> "https://readable.blob.core.windows.net/readable-audio-original/indie-bites-43c183b9-5e59-4611-af66-7bea4520d07f.mp3?sv=2020-12-06&st=2022-10-31T07%3A30%3A00Z&se=2022-11-01T07%3A30%3A00Z&sr=b&sp=r&sig=aXvkra%2FBU9jCoduZa07W4MTOVQB9oNOdsdySDtPRKWo%3D"
> ```

I just pulled your branch and tested locally and it seems to be working for me too without any changes. Sorry for adding to the confusion, and thanks for testing!

**Comment by jakobht** [comment]
I just tried installing Azurite via npm instead of via VsCode, and that works with the code as is, so I think my VsCode Azurite is somehow broken.
I'm really sorry for the confusion.
I'll approve and merge this PR now.

Thank you for all the work! Truly appreciate it.

**Review by jakobht — APPROVED** [review]

**Pull request merged**
